#if !canImport(ObjectiveC)
import XCTest

extension LocalizablesGeneratorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LocalizablesGeneratorTests = [
        ("testLocalizablesDoesNothingForEmpty", testLocalizablesDoesNothingForEmpty),
        ("testLocalizablesSuccessfullySavedEmptyFileForEmptyStrings", testLocalizablesSuccessfullySavedEmptyFileForEmptyStrings),
        ("testLocalizablesSuccessfullySavedForAllLanguages", testLocalizablesSuccessfullySavedForAllLanguages),
    ]
}

extension ManifestGeneratorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ManifestGeneratorTests = [
        ("testSaveEmptyManifestSuccessfullyForEpmtyDirectory", testSaveEmptyManifestSuccessfullyForEpmtyDirectory),
        ("testSaveManifestFailedForNotExistingDirectory", testSaveManifestFailedForNotExistingDirectory),
        ("testSaveManifestSuccessfullyForNotEpmtyDirectory", testSaveManifestSuccessfullyForNotEpmtyDirectory),
    ]
}

extension PassGeneratorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PassGeneratorTests = [
        ("testGeneratePassSuccessfully", testGeneratePassSuccessfully),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LocalizablesGeneratorTests.__allTests__LocalizablesGeneratorTests),
        testCase(ManifestGeneratorTests.__allTests__ManifestGeneratorTests),
        testCase(PassGeneratorTests.__allTests__PassGeneratorTests),
    ]
}
#endif
